version: "3.9"

services:
  php-fpm:
    build: .
    container_name: aio-php-fpm
    volumes:
      - ./:/var/www/html
    networks:
      - appnet

  nginx:
    image: nginx:1.27-alpine
    container_name: aio-nginx
    ports:
      - "8080:80"
    volumes:
      - ./conf/nginx/nginx-site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/html:ro
    depends_on:
      - php-fpm
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
