services:
  - type: web
    name: laravel-app
    runtime: docker
    env: docker
    plan: free
    dockerfilePath: docker/php/Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://aio-app-services.onrender.com/
      - key: PORT
        value: 8080

      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-db-host.onrender.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your-db-name
      - key: DB_USERNAME
        value: your-db-user
      - key: DB_PASSWORD
        value: your-db-password

      - key: REDIS_CLIENT
        value: phpredis
      - key: REDIS_URL
        value: redis://default:NBnWPEGCjICGZo0sGC0gpw0s0TxCnK9P@redis-11707.crce185.ap-seast-1-1.ec2.redns.redis-cloud.com:11707

    buildCommand: |
      cd app
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache

    startCommand: |
      cd app
      php artisan migrate --force
      nginx -g "daemon off;"
